image: fedora:rawhide

variables:
  DEPENDENCIES: gcc gcc-c++ glibc-devel make libxml2-devel glib2-devel
                automake autoconf gettext intltool git

build:
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    # Compile xdgmime
    - git clone https://gitlab.freedesktop.org/xdg/xdgmime.git
    - cd xdgmime
    - make
    - cd ..
    # Compile and test shared-mime-info with builddir != srcdir
    - mkdir build
    - cd build
    - XDGMIME_PATH=`pwd`/../xdgmime/ ../autogen.sh --disable-dependency-tracking
    - make
    - make check
    - make distcheck
    - make install
    # Compile and test with builddir == srcdir
    - make uninstall
    - cd ..
    - rm -rf build/
    - XDGMIME_PATH=`pwd`/xdgmime/ ./autogen.sh
    - make check
    - make distcheck
